packages:
  - "examples/*"
  - "packages/*"
  - "e2e"

catalog:
  "@btst/stack": "1.1.11"
  "react": "^19.2.1"
  "react-dom": "^19.2.1"
  "@tanstack/react-query": "^5.90.12"
  "sonner": "^2.0.1"
  "typescript": "^5.7.3"
